FROM mcr.microsoft.com/devcontainers/python:1-3.12

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    # Additional library needed by some tests and accordingly by VScode Tests Discovery
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install uv
RUN pip3 install uv

WORKDIR /usr/src

USER vscode
ENV VIRTUAL_ENV="/home/vscode/.local/python-venv"
RUN uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /tmp

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash